Added colored shell prompt

diff --git a/openwrtimagebuilder b/openwrtimagebuilder
--- a/openwrtimagebuilder
+++ b/openwrtimagebuilder
@@ -136,6 +136,71 @@ dnsmasq:x:0:0:99999:7:::
 EOL
 echo -e "End login credentials.\n"
 
+# configure shell
+echo -e "\nBegin shell config."
+cat <<'EOL' | tee "$workdir"/files/etc/profile
+#!/bin/sh
+[ -e /tmp/.failsafe ] && export FAILSAFE=1
+
+[ -f /etc/banner ] && cat /etc/banner
+[ -n "$FAILSAFE" ] && cat /etc/banner.failsafe
+
+fgrep -sq '/ overlay ro,' /proc/mounts && {
+        echo 'Your JFFS2-partition seems full and overlayfs is mounted read-only.'
+        echo 'Please try to remove files from /overlay/upper/... and reboot!'
+}
+
+export PATH="/usr/sbin:/usr/bin:/sbin:/bin"
+export HOME=$(grep -e "^${USER:-root}:" /etc/passwd | cut -d ":" -f 6)
+export HOME=${HOME:-/root}
+export PS1='\[\e[1;32m\][\[\e[1;37m\]\u@\h \[\e[1;35m\]\w\[\e[1;32m\]]\[\e[1;31m\]\\$\[\e[m\] '
+
+case "$TERM" in
+        xterm*|rxvt*)
+                export PS1='\[\e]0;\u@\h: \w\a\]'$PS1
+                ;;
+esac
+
+[ -x /bin/more ] || alias more=less
+[ -x /usr/bin/vim ] && alias vi=vim || alias vim=vi
+
+alias ll='ls -alF --color=auto'
+
+[ -z "$KSH_VERSION" -o \! -s /etc/mkshrc ] || . /etc/mkshrc
+
+[ -x /usr/bin/arp -o -x /sbin/arp ] || arp() { cat /proc/net/arp; }
+[ -x /usr/bin/ldd ] || ldd() { LD_TRACE_LOADED_OBJECTS=1 $*; }
+
+[ -n "$FAILSAFE" ] || {
+        for FILE in /etc/profile.d/*.sh; do
+                [ -e "$FILE" ] && . "$FILE"
+        done
+        unset FILE
+}
+
+if ( grep -qs '^root::' /etc/shadow && \
+     [ -z "$FAILSAFE" ] )
+then
+cat << EOF
+=== WARNING! =====================================
+There is no root password defined on this device!
+Use the "passwd" command to set up a new password
+in order to prevent unauthorized SSH logins.
+--------------------------------------------------
+EOF
+fi
+
+service() {
+        [ -f "/etc/init.d/$1" ] || {
+                echo "service "'"'"$1"'"'" not found, the following services are available:"
+                ls "/etc/init.d"
+                return 1
+        }
+        /etc/init.d/$@
+}
+EOL
+echo -e "End shell config.\n"
+
 # create dnsmasq configs and disable win2k filtering (which breaks jabber/xmpp)
 echo -e "\nBegin dnsmasq config."
 cat <<'EOL' | tee "$workdir"/files/etc/config/dhcp
